// src/components/RadarWebView.tsx
import React, { useRef, useEffect, useState, useMemo } from "react";
import CloseButton from "./CloseButton";
import { useLanguage } from "../src/context/LanguageContext";
import { WeatherData, Settings, TemperatureUnit } from "../types";

interface Props {
  location: string;
  weatherData: WeatherData;
  settings: Settings;
  onClose: () => void;
}

/**
 * Generate AI Weather Insight for Radar Analysis
 * Same logic as RadarMap.tsx for consistency
 */
function generateRadarInsight(
  current: any,
  temp: number,
  unit: string,
  selectedLayer: "rain" | "wind" | "clouds" | "temperature"
): string {
  const wind = current.windSpeed ?? 0;
  const pressure = current.pressure ?? 1012;
  const humidity = current.humidity ?? 0;
  const condition = (current.condition || "").toLowerCase();
  const visibility = current.visibility ?? null;
  
  const isRainy = condition.includes("rain") || condition.includes("drizzle");
  const isCloudy = condition.includes("cloud") || condition.includes("overcast");
  const isWindy = wind >= 20;
  const isVeryWindy = wind >= 30;
  const hasLowPressure = pressure < 1000;
  const hasHighPressure = pressure > 1020;
  const hasHighHumidity = humidity >= 70;
  const isCold = temp < 10;
  const isHot = temp > 30;
  
  const insights: string[] = [];
  
  // Layer-specific detailed analysis
  if (selectedLayer === "rain") {
    if (isRainy && isCloudy) {
      insights.push("Radar imagery reveals active precipitation systems moving across the region. The dense cloud formations are producing sustained rainfall with varying intensity patterns. Current atmospheric conditions suggest these precipitation cells will continue to develop and move, potentially intensifying in areas where low pressure systems converge.");
    } else if (isCloudy && hasHighHumidity && !isRainy) {
      insights.push("High-resolution radar analysis shows significant cloud density combined with elevated humidity levels, creating optimal conditions for precipitation development. The atmospheric moisture content is reaching critical thresholds, and radar patterns indicate rain formation is likely within the next 2-4 hours as these cloud systems mature and reach saturation points.");
    } else if (hasLowPressure && isCloudy) {
      insights.push("Low pressure systems are actively enhancing cloud formation and increasing precipitation probability across the region. Radar monitoring reveals developing rain cells that are expected to intensify as the pressure gradient strengthens. These conditions typically lead to more widespread and persistent rainfall patterns.");
    } else {
      insights.push("Current radar analysis shows minimal precipitation activity in the region. Atmospheric conditions appear stable with low rain probability. The radar imagery indicates clear skies and stable weather patterns that are expected to persist over the next several hours.");
    }
    
    if (isWindy && isRainy) {
      insights.push("Wind patterns are significantly influencing precipitation distribution. The radar shows rain intensity and location shifting as wind systems evolve. These dynamic conditions mean precipitation patterns will continue to change over the next few hours, with some areas experiencing increased rainfall while others may see clearing conditions.");
    }
  } else if (selectedLayer === "wind") {
    if (hasLowPressure && isWindy) {
      insights.push("Radar wind analysis reveals strong wind patterns generated by the low pressure system. These winds are creating significant atmospheric movement across the region, with speeds that may intensify as the pressure gradient continues to strengthen. The wind patterns are actively redistributing moisture and cloud formations, which will influence precipitation development.");
    } else if (hasHighPressure && !isWindy) {
      insights.push("High pressure dominance is creating calm, stable wind conditions throughout the region. Radar wind data shows light and consistent wind patterns that are expected to persist. These stable conditions typically lead to clear skies and minimal weather disturbances, creating ideal conditions for extended periods of calm weather.");
    } else if (isVeryWindy) {
      insights.push("Strong wind patterns are dominating the regional weather system, as evidenced by radar wind analysis. These powerful winds are significantly influencing cloud movement, precipitation distribution, and overall atmospheric dynamics. The wind patterns suggest active weather systems that will continue to evolve and potentially intensify.");
    } else {
      insights.push("Radar wind analysis indicates moderate and stable wind patterns across the region. Current wind speeds suggest calm atmospheric conditions with minimal turbulence. These moderate winds are providing stable weather patterns that are expected to continue without significant changes in the near term.");
    }
    
    if (isWindy && isCloudy) {
      insights.push("Wind patterns are actively moving cloud systems across the region. Radar imagery shows these winds are reorganizing cloud formations, which will result in shifting weather patterns. The interaction between wind and cloud systems creates dynamic conditions that will continue to evolve over the next several hours.");
    }
  } else if (selectedLayer === "clouds") {
    if (isCloudy && hasHighHumidity) {
      insights.push("Radar cloud analysis reveals dense cloud coverage combined with high humidity levels, creating optimal conditions for significant precipitation development. The cloud systems are mature and capable of producing substantial rainfall. These conditions, when combined with the high atmospheric moisture content, indicate a high probability of sustained precipitation activity.");
    } else if (isCloudy && isRainy) {
      insights.push("Extensive cloud cover is actively producing precipitation across the region. Radar imagery shows dense cloud formations that are generating sustained rainfall. The cloud density and movement patterns indicate that precipitation activity will continue, with intensity variations as cloud systems move and evolve.");
    } else if (isCloudy && !hasHighHumidity) {
      insights.push("Cloud formation is present across the region, though humidity levels remain moderate. Radar analysis suggests these cloud systems are still developing, with moderate precipitation probability. The cloud patterns indicate ongoing atmospheric processes that may lead to increased precipitation as conditions mature.");
    } else {
      insights.push("Radar cloud analysis shows minimal cloud coverage, indicating clear atmospheric conditions throughout the region. The low cloud density suggests stable weather with limited precipitation potential. These clear conditions are expected to persist, providing extended periods of favorable weather.");
    }
    
    if (isWindy && isCloudy) {
      insights.push("Wind patterns are actively dispersing and reorganizing cloud systems across the region. Radar imagery shows these winds are creating dynamic cloud movements that will continue to evolve. The interaction between wind and cloud systems is creating changing weather patterns that will develop over the next several hours.");
    }
  } else if (selectedLayer === "temperature") {
    if (isHot && hasHighHumidity) {
      insights.push("Temperature analysis reveals elevated temperatures combined with high humidity, creating unstable atmospheric conditions that favor convective cloud development. These thermal and moisture conditions are prime for thunderstorm formation, as the atmosphere becomes increasingly unstable. Radar monitoring shows these conditions may lead to rapid weather development.");
    } else if (isCold && hasHighHumidity) {
      insights.push("Cold temperatures combined with high humidity are creating conditions favorable for fog formation and reduced visibility. Radar analysis indicates that precipitation may transition to freezing conditions if temperatures continue to drop. These cold, moist conditions typically lead to persistent low-visibility situations.");
    } else if (isHot && !isCloudy) {
      insights.push("High temperatures with clear skies indicate stable atmospheric conditions. Radar temperature analysis shows heat patterns that may intensify during peak hours with minimal cloud interference. These conditions suggest extended periods of warm, clear weather with stable thermal patterns.");
    } else if (isCold && hasHighPressure) {
      insights.push("Cold temperatures with high pressure indicate stable, clear conditions throughout the region. Radar analysis suggests temperature inversions may occur, trapping cold air near the surface. These conditions typically lead to extended periods of cold, clear weather with minimal atmospheric disturbances.");
    } else {
      insights.push("Temperature patterns across the region are moderate and stable. Radar thermal analysis indicates balanced atmospheric conditions that suggest continued stability. These moderate temperatures provide comfortable conditions with minimal weather-related concerns.");
    }
    
    if (hasLowPressure && isHot) {
      insights.push("Low pressure combined with high temperatures creates favorable conditions for convective activity and potential thunderstorm development. Radar analysis shows these thermal and pressure conditions may lead to rapid weather changes as thermal energy accumulates in the atmosphere.");
    }
  }
  
  // Cross-layer comprehensive analysis
  if (hasLowPressure && isCloudy && hasHighHumidity) {
    insights.push("Comprehensive radar analysis reveals a convergence of atmospheric conditions that strongly favor significant weather development. The combination of low pressure, high cloud density, and elevated humidity creates a high-probability scenario for sustained precipitation within the next 2-3 hours. These conditions suggest active weather systems that will continue to develop and intensify.");
  } else if (hasHighPressure && !isCloudy) {
    insights.push("Radar analysis across all layers indicates high pressure dominance with clear conditions, suggesting stable weather patterns that will persist. The atmospheric stability shown in the radar data suggests no significant weather changes are expected in the short term, providing extended periods of favorable conditions.");
  }
  
  // Visibility conditions
  if (visibility !== null && visibility < 5) {
    insights.push("Radar analysis indicates reduced visibility conditions are present across the region. These conditions may be due to fog, precipitation, or atmospheric moisture affecting regional clarity. Visibility improvements are expected as atmospheric conditions stabilize.");
  }
  
  // Fallback
  if (insights.length === 0) {
    insights.push("Comprehensive radar analysis of current atmospheric conditions is ongoing. Weather patterns appear stable with no immediate significant changes expected. The radar data suggests continued stability across all monitored parameters.");
  }
  
  return insights.join(" ");
}

/**
 * Typing Animation Component for AI Insight
 */
function TypingAnimation({ text }: { text: string }) {
  const [displayedText, setDisplayedText] = useState("");
  const [isComplete, setIsComplete] = useState(false);

  useEffect(() => {
    setDisplayedText("");
    setIsComplete(false);
    let currentIndex = 0;

    const typingInterval = setInterval(() => {
      if (currentIndex < text.length) {
        setDisplayedText(text.slice(0, currentIndex + 1));
        currentIndex++;
      } else {
        setIsComplete(true);
        clearInterval(typingInterval);
      }
    }, 15);

    return () => clearInterval(typingInterval);
  }, [text]);

  return (
    <div className="text-sm leading-relaxed text-white/95">
      {displayedText}
      {!isComplete && <span className="animate-pulse text-amber-400">|</span>}
    </div>
  );
}

/**
 * RadarWebView - Wrapper component for web-based radar map
 * Embeds radar.html in an iframe and provides native UI controls
 */
export default function RadarWebView({ location, weatherData, settings, onClose }: Props) {
  const { t } = useLanguage();
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [coordinates, setCoordinates] = useState<[number, number] | null>(null);
  const [isPlaying, setIsPlaying] = useState<boolean>(true);
  const [selectedLayer, setSelectedLayer] = useState<"rain" | "wind" | "clouds" | "temperature">("rain");

  // Extract coordinates from location
  useEffect(() => {
    if (!location) return;

    const latLonMatch = location.match(/^\s*(-?\d+(\.\d+)?)\s*,\s*(-?\d+(\.\d+)?)\s*$/);
    if (latLonMatch) {
      const lat = parseFloat(latLonMatch[1]);
      const lon = parseFloat(latLonMatch[3]);
      if (!isNaN(lat) && !isNaN(lon)) {
        setCoordinates([lat, lon]);
      }
    }
  }, [location]);

  // Send coordinates to iframe when they change
  useEffect(() => {
    if (iframeRef.current && coordinates) {
      const iframe = iframeRef.current;
      // Wait for iframe to load before sending messages
      const timer = setTimeout(() => {
        iframe.contentWindow?.postMessage(
          {
            type: "updateCenter",
            lat: coordinates[0],
            lon: coordinates[1],
          },
          "*"
        );
      }, 1000); // Give iframe time to initialize

      return () => clearTimeout(timer);
    }
  }, [coordinates]);

  // Send play/pause commands to iframe
  useEffect(() => {
    if (iframeRef.current) {
      const iframe = iframeRef.current;
      const timer = setTimeout(() => {
        iframe.contentWindow?.postMessage(
          {
            type: isPlaying ? "play" : "pause",
          },
          "*"
        );
      }, 1000);

      return () => clearTimeout(timer);
    }
  }, [isPlaying]);

  // Build iframe URL with parameters
  const mapboxToken = import.meta.env.VITE_MAPBOX_TOKEN || "";
  const iframeUrl = coordinates
    ? `/radar.html?token=${encodeURIComponent(mapboxToken)}&lat=${coordinates[0]}&lon=${coordinates[1]}&zoom=5`
    : `/radar.html?token=${encodeURIComponent(mapboxToken)}&lat=35&lon=10&zoom=5`;

  // Generate AI Insight with full logic
  const current = weatherData?.current || {};
  const temp = Math.round(current.temperature ?? 0);
  const unit = settings.unit;
  const radarInsight = useMemo(() => {
    return generateRadarInsight(
      current,
      temp,
      unit === TemperatureUnit.CELSIUS ? "C" : "F",
      selectedLayer
    );
  }, [current, temp, unit, selectedLayer]);

  if (!coordinates) {
    return (
      <div className="relative min-h-screen bg-black text-white flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-white"></div>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen bg-black text-white overflow-hidden flex flex-col">
      {/* Close Button - Top Left */}
      <div className="absolute top-4 left-4 z-[1000]">
        <CloseButton onClose={onClose} />
      </div>

      {/* WebView iframe - Full screen radar map */}
      <iframe
        ref={iframeRef}
        src={iframeUrl}
        className="relative flex-1 w-full border-0"
        style={{ minHeight: "50vh" }}
        allow="geolocation"
        title="Radar Map"
      />

      {/* AI Analysis Panel - Native React component */}
      <div className="relative z-[500] px-4 pb-2 pt-4">
        <div
          className="rounded-2xl border border-white/20 shadow-2xl overflow-hidden mx-auto"
          style={{
            background: "rgba(0, 0, 0, 0.5)",
            backdropFilter: "blur(20px)",
            WebkitBackdropFilter: "blur(20px)",
            maxWidth: "100%",
          }}
        >
          <div className="px-5 py-4">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-2xl">🤖</span>
              <div className="font-semibold text-base text-white">
                {t("radar.aiInsight") || "AI Weather Analysis"}
              </div>
            </div>
            <div className="min-h-[80px]">
              <TypingAnimation text={radarInsight} />
            </div>
          </div>
        </div>
      </div>

      {/* Native Controls - Floating minimal controls */}
      <div className="relative z-[500] px-4 pb-4">
        <div className="flex items-center justify-center gap-2 sm:gap-3 flex-wrap mx-auto max-w-2xl">
          <button
            onClick={() => setSelectedLayer("rain")}
            className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl transition-all duration-200 min-w-[70px] ${
              selectedLayer === "rain"
                ? "bg-white/25 text-white shadow-lg scale-105"
                : "bg-white/10 text-white/80 hover:bg-white/15"
            }`}
            style={{
              backdropFilter: "blur(10px)",
              WebkitBackdropFilter: "blur(10px)",
            }}
          >
            <span className="text-xl">🌧</span>
            <span className="text-xs font-medium">{t("radar.rain") || "Rain"}</span>
          </button>

          <button
            onClick={() => setSelectedLayer("wind")}
            className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl transition-all duration-200 min-w-[70px] ${
              selectedLayer === "wind"
                ? "bg-white/25 text-white shadow-lg scale-105"
                : "bg-white/10 text-white/80 hover:bg-white/15"
            }`}
            style={{
              backdropFilter: "blur(10px)",
              WebkitBackdropFilter: "blur(10px)",
            }}
          >
            <span className="text-xl">💨</span>
            <span className="text-xs font-medium">{t("radar.wind") || "Wind"}</span>
          </button>

          <button
            onClick={() => setSelectedLayer("clouds")}
            className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl transition-all duration-200 min-w-[70px] ${
              selectedLayer === "clouds"
                ? "bg-white/25 text-white shadow-lg scale-105"
                : "bg-white/10 text-white/80 hover:bg-white/15"
            }`}
            style={{
              backdropFilter: "blur(10px)",
              WebkitBackdropFilter: "blur(10px)",
            }}
          >
            <span className="text-xl">☁</span>
            <span className="text-xs font-medium">{t("radar.clouds") || "Clouds"}</span>
          </button>

          <button
            onClick={() => setSelectedLayer("temperature")}
            className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl transition-all duration-200 min-w-[70px] ${
              selectedLayer === "temperature"
                ? "bg-white/25 text-white shadow-lg scale-105"
                : "bg-white/10 text-white/80 hover:bg-white/15"
            }`}
            style={{
              backdropFilter: "blur(10px)",
              WebkitBackdropFilter: "blur(10px)",
            }}
          >
            <span className="text-xl">🌡</span>
            <span className="text-xs font-medium">{t("radar.temperature") || "Temperature"}</span>
          </button>

          {/* Play/Pause button */}
          <button
            onClick={() => setIsPlaying(!isPlaying)}
            className={`flex flex-col items-center gap-1 px-3 py-2 rounded-xl transition-all duration-200 min-w-[70px] ${
              isPlaying
                ? "bg-white/25 text-white shadow-lg"
                : "bg-white/10 text-white/80 hover:bg-white/15"
            }`}
            style={{
              backdropFilter: "blur(10px)",
              WebkitBackdropFilter: "blur(10px)",
            }}
          >
            <span className="text-xl">{isPlaying ? "⏸" : "▶"}</span>
            <span className="text-xs font-medium">{isPlaying ? "Pause" : "Play"}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
